name: Cron Job Workflow

on:
  # Allows manual trigger
  workflow_dispatch:
  # Triggers the workflow at 9am / 4pm LA time - from Monday to Friday
  schedule:
    - cron: "0 17 * * 1-5"
    - cron: "0 0 * * 1-5"

jobs:
  cron:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Run work queue command
        id: workqueue
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://smee.io/6a7eTzDyvdduDXo'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json", "Authorization": "Bearer test"}'
      - name: Show Response
        run: |
          echo ${{ steps.workqueue.outputs.response }}
          echo ${{ steps.workqueue.outputs.headers }}